### ISSUE TITLE
List technical solutions for sharing calendars.

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-calendar#254]
Related to:
* Sharing ICS calendar (#206)
* Sharing a public ICS feed (#93)
* Subscribing a public ICS feed (#91)

We must list technical solutions to share calendars before actually implement anything. It should allow to share a calendar with Google, Apple, and Microsoft (maybe others?).

What we already know:
* fullcalendar can support the following format out of the box (read-only): http://fullcalendar.io/docs/event_data/Event_Source_Object/ (array of objects, function generating events, remote JSON feed and Google Calendar feed)
* we can feed fullcalendar with a pure ICS feed, but a proxy ics to json on the app's server should be fairly easy to do.

Things to investigate:
* we could have a CalDav client in Cozy to manage shared calendars.
* there might be a protocol for shared calendars.

ping @aenario

**Comment by aenario** [comment]
So, I did some research involving Outlook.com, Yahoo, Gmail & owncloud

There is 3 use cases to consider 

### SYNCHRO WITH ONE's OWN SERVICES
#### ie. "I am getting started with cozy, but i want to keep my calendar on outlook at the beginning"

It could be achieved through caldav, but not compatible with hotmail. 
The best option will probably be to use the user's smartphone as a data source through the cozy-mobile app, because the phone already contains & normalizes the user accounts. 

### SHARING A CALENDAR WITH A FRIEND  (Write access)
#### ie. "I want a calendar where both me and my colleagues can add events"

There is currently no standard supported by major players to do this. Yahoo & Gmail doesnt support giving access only to some calendar through CalDAV. Hotmail doesnt support CalDAV at all. The commonly accepted methods is to send invitations through .ics files by mail. (Ref https://github.com/cozy/cozy-emails/issues/433), combined with read sharing.

For the cozy-to-cozy case, if we want to make something fast before the DecSharing CG, it will be way easier to make an ad-hoc REST API  than to try to support ACLs in cozy-sync & make a caldav client.

### SHARING A CALENDAR WITH A FRIEND (Read access)
#### ie. "I want some of my friends to be able to see my "poker nights" calendar"

Current standard, supported by all except owncloud (?) , is to share the URL to a .ics file with some security token included in the URL.

### Conclusion & actionable
- Allow to synchronize (read-only) a .ics URL with a cozy calendar (the calendar should be read-only in cozy) OR display the content of a .ics URL in the calendar interface (with cache ?)
- Allow to export & share a calendar through a public .ics URL using cozy-clearance

**Comment by jsilvestre** [comment]
I guess we can close the issue. Thank you!
