### ISSUE TITLE
Improve default colors for new calendars

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-calendar#256]
There should be a predefined set of colours (like 16-24) to pick in.

**Comment by kelukelu** [comment]
Here is the first shot of the color palette:
![palette calendar 01](https://cloud.githubusercontent.com/assets/7029620/7930345/d4fab790-0907-11e5-83d2-735b185b9d66.png)
@jsilvestre what do you think?

**Comment by jsilvestre** [comment]
I think you will know my name is the lord when I lay my vengeance upon you :)

It looks good to me, let's show the world if someone has something to say.

**Comment by m4dz** [comment]
:+1:

**Comment by frankrousseau** [comment]
+1

**Comment by Benibur** [comment]
Is it possible to see it with the seame size font as in the app ?
I thing the the light blue in the middle and ent two on the right will be difficult to read.
maybe instead of a color each "color" should be a pair, one for the background, one for the font.
Otherwise it looks great, you will have to adapt the rest of the app in consequence :-)

**Comment by kelukelu** [comment]
Here we go, with the same font size as in Calendar:
![palette calendar 02](https://cloud.githubusercontent.com/assets/7029620/7936489/b07b6bc6-0939-11e5-8178-1298b2bfe94e.jpg)

**Comment by kelukelu** [comment]
@jsilvestre Here are the hexadecimals to add some rainbow in your life:
#304FFE 
#2979FF
#00B0FF
#00E5FF
#00D5B8
#00C853
#64DD17
#AEEA00
#FFD000
#FFAB00
#FF6D00
#E70505
#FF2828
#F819AA
#AA00FF
#6200EA
#7190AB
#51658D

**Comment by poupotte** [comment]
Color palette is nice. Thanks @kelukelu  and @jsilvestre :)
