### ISSUE TITLE
Renaming a calendar freezes the browser

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#296]
[Reported on the forum](https://forum.cozy.io/t/calendar-crash-lors-de-renommage/777).

**Comment by jsilvestre** [comment]
I tested this with 500 events. It's slow, but it's working (the renaming). The user experience, on the other hand is bad: since it's too long, the request timeouts, so basically nothing happens, the user thinks it has failed, but the data system keeps updating events.

What should be done:
* there are two requests to the server to rename the calendar. One is enough, the other must be prevented.
* server should responds before it begins the actual updates, then forward through websocket the progress.
* in the client, we should block the UI in the meantime to prevent update conflict.
* there is a strange behaviour in the client that makes it spams POST /tags when bulk actions are performed, like renaming a calendar. There should only be one request, not one by event.

Since this issue is not at the top of the priority list, I let it as-is.

BTW the design (each event stores its calendar) is fucked up performance-wise, but I take responsibility for that :)

**Comment by aenario** [comment]
Regarding the design : 
How about we keep the tag "name" as immutable and change its "displayName" throught the Tag doctype. I believe we did it for another apps ?

**Comment by clochix** [comment]
The same is true when trying to delete a calendar with hundreds of events. On Firefox, the browser keeps complaining of a script consuming too much CPU.

**Comment by poupotte** [comment]
This issue should be now fixed.
