### ISSUE TITLE
Week view : Title format in French (localization)

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-calendar#394]
Currently, the week view is labeled as "août 31 - sept. 6 2015" which is just a poor translation of the English label. It should be labeled "31 août - 6 sept. 2015" instead.

**Comment by clochix** [comment]
Thanks for reporting @f6fvy,

We use a third party component to display the calendar, and this component manage the localization part. According to http://fullcalendar.io/js/fullcalendar-2.4.0/demos/languages.html this issue seems to have been fixed upstream, so it should be fixed once we update the calendar component.

**Comment by jsilvestre** [comment]
It's been changed in the latest version, and it's not the case anymore, therefore I close the issue.
