### ISSUE TITLE
Do not allow delete of entire calendar via CalDAV

### ISSUE THREAD

**Issue by drschwabe** [cozy/cozy-calendar#396]
There's a problem I've encountered twice now in that an entire calendar is inadvertently deleted.   It seems to be happening over iOS when you attempt to remove a calendar from your device it actually deletes everything on the remote side (even though, as a user you are thinking just remove it from your device NOT the server). 

I'm sort of basing this off of a theoretical situation cause I have not reproduced the issue directly - but my calendars are being deleted and it's not from the web interface so this is most likely what is happening.   Seems to always happen when another user is trying to setup/configure the calendar on their device (I'm sharing the calendar with multiple users). 

Anyway, it would be great if there was something in place where you can't delete the entire calendar via CalDAV!  A single event yes, but not the entire calendar all in one shot.   Deleting the entire calendar should be something you can only do from the web interface.

**Comment by jsilvestre** [comment]
It's been a while since you've posted the issue, and we never took the time to answer you properly, sorry about that.
The problem is that there is no way for us to know if the user has deleted a calendar or just many events. From the synchronization app point of view, the user has deleted many events, therefore they should be deleted on the remote server too.
Anyway, even if we could know, it's how synchronization work, and I am afraid we can't do anything about it.

Cheers!
