### ISSUE TITLE
Event description not saved

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-calendar#448]
**Steps to reproduce:**

0. Open an event
0. Click on "More options"
0. Type something (the description field should have the focus)
0. Save

**What happens:**

The description is not saved.

However, if I click on the description field, type something, click on "Done" and then on "Save", the description is saved.

**Comment by clochix** [comment]
Thanks for reporting @nicofrand, we'll fix this!

**Comment by jsilvestre** [comment]
The expected behaviour is not to be able to type directly in the field, but rather open the description screen when you click on it. @nicofrand would you mind trying again and let us know if you can still reproduce this issue? If so, please give us your information (browser) so we can reproduce and fix it.

Thank you in advance, cheers.

**Comment by nicofrand** [comment]
@jsilvestre I do **NOT** click on the field (it opens the description if I do). I currently do not need to click on it since it already has the focus when I click on "More options".

I can reproduce it with Firefox 44.0b7, 43.0.x (latest stable) and Chrome (latest) on Ubuntu (14.10 and latest).

**Comment by poupotte** [comment]
This issue is now fixed with new Calendar version (1.0.37)
